### ISSUE TITLE
Fails to checkout Triton.Conn in production

### ISSUE THREAD

**Issue by octavonce** [blitzstudios/triton#40]
Hi,

We have recently deployed Apache Cassandra in production using Triton. While in development mode everything works fine, when deployed we receive the following error when an insert is performed:
```
2020-08-04T10:38:17.831100701Z ** (stop) exited in: GenServer.call(Triton.Conn, :checkout, 5000)
2020-08-04T10:38:17.831105169Z ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
2020-08-04T10:38:17.831129265Z (elixir 1.10.2) lib/gen_server.ex:1013: GenServer.call/3
2020-08-04T10:38:17.831135956Z (xandra 0.13.1) lib/xandra/cluster.ex:390: Xandra.Cluster.with_conn/2
2020-08-04T10:38:17.831140657Z (stdlib 3.11.2) timer.erl:166: :timer.tc/1
2020-08-04T10:38:17.831145119Z  (triton 0.2.4) lib/triton/apm/apm.ex:62: Triton.APM.execute/1
2020-08-04T10:38:17.831149428Z (triton 0.2.4) lib/triton/executor.ex:221: Triton.Executor.execute_on_cluster/3
2020-08-04T10:38:17.831153969Z (triton 0.2.4) lib/triton/executor.ex:142: Triton.Executor.execute/2
```

The cluster connection is fine and I'm unable to tell what the issue is. Any help would be much appreciated!

**Comment by octavonce** [comment]
Nevermind, the issue was that I was configuring Triton at run-time while it only accepts compile-time configuration.

**Comment by sahilpaudel-pe** [comment]
Hi @octavonce Can you please help me understand your issue.
I am trying to use it in production.

Thanks.

**Comment by octavonce** [comment]
@sahilpaudel-pe The Triton application is started earlier than the main app's supervision tree. We would pass configuration to triton at application start which would not get loaded, meaning the app wouldn't connect to the cassandra cluster resulting in the error above.  The solution was to pass configuration to Triton at compile-time via `config.exs`.

**Comment by sahilpaudel-pe** [comment]
You mean this way?

```
config :triton,
  clusters: [
    [
      conn: Triton.Conn,
      nodes: ["127.0.0.1"],
      pool: Xandra.Cluster,
      underlying_pool: DBConnection.Poolboy,
      pool_size: 10,
      keyspace: "keyspace_audit_log",
      health_check_delay: 2500,  # optional: (default is 5000)
      health_check_interval: 500  # optional: (default is 1000)
    ]
  ]
```

I am getting similar error with this too.

**Comment by octavonce** [comment]
@sahilpaudel-pe Yes it's set up exactly like that. Maybe check you Xandra version? We use `{:xandra, "~> 0.12"}`

**Comment by sahilpaudel-pe** [comment]
I am using the latest version `{:xandra, "~> 0.2"}`
