### ISSUE TITLE
Authentication support for Triton

### ISSUE THREAD

**Issue by Relrin** [blitzstudios/triton#9]
Hello,

I'm curious about using this library in my own project however didn't find any documentation (and in the code as well) to authenticate via login/password with a Cassandra instance. Does the Triton package have a support of it? I'd like to work with this feature something like this:

1. Specify credentials in a configuration file:
```bash
config :triton,
  clusters: [
    [
      conn: Triton.Conn,
      nodes: ["127.0.0.1"],
      auth_type: Xandra.Authenticator.Password,  # Using the password method
      auth_credentials: [username: “foo”, password: “bar”],  # and credentials for getting an access 
      pool: Xandra.Cluster,
      underlying_pool: DBConnection.Poolboy,
      pool_size: 10,
      keyspace: "my_keyspace",
      health_check_delay: 2500,  # optional: (default is 5000)
      health_check_interval: 500  # optional: (default is 1000)
    ]
  ]
```
2. Delegate the extracted options to the setup call, so that we can pass it and reuse later:
```elixir
Xandra.start_link(nodes: [...], authentication: {auth_type, authenticator_options})
```

Hovewer in actual moment of time you will receive an error when trying to connect to the Cassandra node that requires credetials:
```
09:53:32.569 [error] GenServer #PID<0.351.0> terminating
** (RuntimeError) Cassandra server requires authentication but the :authentication option was not provided
    (xandra) lib/xandra/protocol.ex:65: Xandra.Protocol.encode_request/3
    (xandra) lib/xandra/connection/utils.ex:70: Xandra.Connection.Utils.authenticate_connection/4
    (xandra) lib/xandra/cluster/control_connection.ex:43: Xandra.Cluster.ControlConnection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: %Xandra.Cluster.ControlConnection{address: 'cassandra', buffer: "", cluster: #PID<0.349.0>, new: true, node_ref: #Reference<0.3298420290.4204789761.220785>, options: [prepared_cache: #Reference<0.3298420290.4204920833.220784>, idle_timeout: 30000, after_connect: #Function<0.29847296/1 in Triton.Supervisor.init/1>, conn: Short.DTCS.Connection, pool_size: 10, keyspace: "short_dtcs_keyspace", health_check_delay: 5000, health_check_interval: 500], port: 9042, socket: nil}
 
09:53:32.571 [error] GenServer #PID<0.350.0> terminating
** (RuntimeError) Cassandra server requires authentication but the :authentication option was not provided
    (xandra) lib/xandra/protocol.ex:65: Xandra.Protocol.encode_request/3
    (xandra) lib/xandra/connection/utils.ex:70: Xandra.Connection.Utils.authenticate_connection/4
    (xandra) lib/xandra/cluster/control_connection.ex:43: Xandra.Cluster.ControlConnection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.349.0>, {%RuntimeError{message: "Cassandra server requires authentication but the :authentication option was not provided"}, [{Xandra.Protocol, :encode_request, 3, [file: 'lib/xandra/protocol.ex', line: 65]}, {Xandra.Connection.Utils, :authenticate_connection, 4, [file: 'lib/xandra/connection/utils.ex', line: 70]}, {Xandra.Cluster.ControlConnection, :connect, 2, [file: 'lib/xandra/cluster/control_connection.ex', line: 43]}, {Connection, :enter_connect, 5, [file: 'lib/connection.ex', line: 622]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: {:state, {#PID<0.350.0>, Supervisor.Default}, :one_for_one, [], :undefined, 0, 5, [], 0, Supervisor.Default, {:ok, {%{intensity: 0, period: 5, strategy: :one_for_one}, []}}}
```

**Comment by Relrin** [comment]
Okay, I've figured out how to deal with it. For using auth features (or anything else) a developer must specify other keywords as is. For example it can be looks like this in your `config.exs`:

```elixir
config :triton,
  clusters: [
    [
      conn: Short.DTCS.Connection,
      authentication: {
        Xandra.Authenticator.Password,
        [
          username: System.get_env("CASSANDRA_USERNAME") || "cassandra",
          password: System.get_env("CASSANDRA_PASSWORD") || "cassandra"
        ]
      },
      nodes: [System.get_env("CASSANDRA_CLUSTER_ADDRESS") || "127.0.0.1"],
      pool: Xandra.Cluster,
      underlying_pool: DBConnection.Poolboy,
      pool_size: 10,
      keyspace: "short_dtcs_keyspace",
      health_check_delay: 5000,
      health_check_interval: 500
    ]
  ]
```

So, nonetheless, it will be great to add any documentation about this, if any other developer (like me) will face with the same issue later.
